// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortariaInteligente.Data;

namespace PortariaInteligente.Migrations
{
    [DbContext(typeof(PortariaInteligenteContext))]
    [Migration("20200104103012_erroDocumentoID")]
    partial class erroDocumentoID
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PortariaInteligente.Models.Anfitriao", b =>
                {
                    b.Property<int>("AnfitriaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("celAnfitriao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailAnfitriao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fixoAnfitriao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeAnfitriao")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("senhaAnfitriao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tokenAnfitiao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnfitriaoId");

                    b.ToTable("Anfitriaos");
                });

            modelBuilder.Entity("PortariaInteligente.Models.Documento", b =>
                {
                    b.Property<int>("DocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nomeDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentoId");

                    b.ToTable("documentos");
                });

            modelBuilder.Entity("PortariaInteligente.Models.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnfitriaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataEvento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("horaEvento")
                        .HasColumnType("datetime2");

                    b.Property<string>("localEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventoId");

                    b.HasIndex("AnfitriaoId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("PortariaInteligente.Models.Evento", b =>
                {
                    b.HasOne("PortariaInteligente.Models.Anfitriao", "anfitriao")
                        .WithMany()
                        .HasForeignKey("AnfitriaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
