// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortariaInteligente.Data;

namespace PortariaInteligente.Migrations
{
    [DbContext(typeof(PortariaInteligenteContext))]
    [Migration("20200104103516_Retomando")]
    partial class Retomando
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PortariaInteligente.Models.Anfitriao", b =>
                {
                    b.Property<int>("AnfitriaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("celAnfitriao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailAnfitriao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fixoAnfitriao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeAnfitriao")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("senhaAnfitriao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tokenAnfitiao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnfitriaoId");

                    b.ToTable("Anfitrioes");
                });

            modelBuilder.Entity("PortariaInteligente.Models.Convidado", b =>
                {
                    b.Property<int>("ConvidadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("celConvidado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("corCarro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailConvidado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("marcaCarro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modeloCarro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeConvidado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numeroDoctoConvidado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("placaCarro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConvidadoId");

                    b.HasIndex("DocumentoId");

                    b.ToTable("Convidados");
                });

            modelBuilder.Entity("PortariaInteligente.Models.ConvidadoEvento", b =>
                {
                    b.Property<int>("ConvidadoEventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConvidadoId")
                        .HasColumnType("int");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.HasKey("ConvidadoEventoId");

                    b.HasIndex("ConvidadoId");

                    b.HasIndex("EventoId");

                    b.ToTable("ConvidadoEventos");
                });

            modelBuilder.Entity("PortariaInteligente.Models.Documento", b =>
                {
                    b.Property<int>("DocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nomeDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentoId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("PortariaInteligente.Models.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnfitriaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataEvento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("horaEvento")
                        .HasColumnType("datetime2");

                    b.Property<string>("localEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventoId");

                    b.HasIndex("AnfitriaoId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("PortariaInteligente.Models.Convidado", b =>
                {
                    b.HasOne("PortariaInteligente.Models.Documento", "NomeDocumento")
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortariaInteligente.Models.ConvidadoEvento", b =>
                {
                    b.HasOne("PortariaInteligente.Models.Convidado", "convidado")
                        .WithMany()
                        .HasForeignKey("ConvidadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortariaInteligente.Models.Evento", "evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortariaInteligente.Models.Evento", b =>
                {
                    b.HasOne("PortariaInteligente.Models.Anfitriao", "anfitriao")
                        .WithMany()
                        .HasForeignKey("AnfitriaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
